apiVersion: v1
kind: Template
metadata:
  name: gitlab-mirror
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
    labels:
      template: gitlab-mirror
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${NAME}
    labels:
      template: gitlab-mirror
  spec:
    completionDeadlineSeconds: "1800"
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/rht-labs/tools.git
      contextDir: /image
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Secret
  metadata:
    name: gitlab-secret
    labels:
      template: gitlab-mirror
  stringData:
    source_gitlab_url: ${SOURCE_GITLAB_URL}
    source_gitlab_token: ${SOURCE_GITLAB_TOKEN}
    source_gitlab_user: ${SOURCE_GITLAB_USER}
    dest_gitlab_token: ${DEST_GITLAB_TOKEN}
    dest_gitlab_user: ${DEST_GITLAB_USER}
    dest_repository: ${DEST_REPOSITORY}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: SOURCE_GITLAB_URL
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: source_gitlab_url
          - name: SOURCE_GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: source_gitlab_token
          - name: SOURCE_GITLAB_USER
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: source_gitlab_user
          - name: DEST_GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: dest_gitlab_token
          - name: DEST_GITLAB_USER
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: dest_gitlab_user
          - name: DEST_REPOSITORY
            valueFrom:
              secretKeyRef:
                name: gitlab-secret
                key: dest_repository
          image: ' '
          name: ${NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - gitlab-mirror
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: gitlab-mirror
- name: NAMESPACE
  displayName: "Namespace where this is deployed"
  description: "Namespace where this is deployed."
  value: "cluster-ops"
  required: true
- name: SOURCE_GITLAB_URL
  displayName: Source GitLab Web URL
  description: Source GitLab Web URL
  value: ""
  required: true
- name: SOURCE_GITLAB_TOKEN
  displayName: Source GitLab Access Token
  description: Source GitLab Access Token
  value: ""
  required: true
- name: SOURCE_GITLAB_USER
  displayName: Source GitLab user
  description: Source GitLab user
  value: ""
  required: true
- name: DEST_REPOSITORY
  displayName: Destination GitLab HTTPS url
  description: Destination GitLab HTTPS url
  value: ""
  required: true
- name: DEST_GITLAB_TOKEN
  displayName: Destination GitLab Access Token
  description: Destination GitLab Access Token
  value: ""
  required: true
- name: DEST_GITLAB_USER
  displayName: Destination GitLab user
  description: Destination GitLab user
  value: ""
  required: true